#list data
list_hari = ["SENIN", "SELASA", "RABU", "KAMIS", "JUM'AT"]
list_waktu= ["08:00-09:40", "09:45-11:25", "12:30-14:10", "13:15-16:00"]
list_kelas = ["kelas 2a", "kelas 2b", "kelas 2c", "kelas 2d", "kelas 2e", "kelas 2f", "kelas 2g", "kelas 2h",
			 "LAB 3a", "LAB 3b", "kelas 3c", "kelas 3d"]
list_dosen = ["LANDUNG SUDARMANA, S.T.,M.Kom", "SITI FIATUL HASANAH, S.Pd", "ADKHAN SHOLEH, S.Si.,M.Cs", 
			"PUJI WINAR CAHYO, S.Kom.,M.Cs", "RAGIL SURYO RAHARJO, S.Fil", "INDRATI HENDRIK, S.T.h.", "ARIF HIMAWAN, S.Kom.,M.M.,M.",
 			"ALFIRNA RIZQI LAHITANI, S..Kom.,M.Eng", "TITIK RAHMAWATI, S.T.,M.Cs", "ALI ASMU’I, S.Ag.,M.Pd", "AGUNG WIDODO, S.s., M.P.d"]
list_mapel = ["LOGIKA INFORMATIKA", "BAHASA INGGRIS I", "PRAKTIKUM APLIKASI KOMPUTER I ", "KONSEP PEMEROGRAMAN", 
			"PENDIDIKAN PANCASILA", "PENDIDIKAN AGAMA KRISTEN","DESIGN THINGKING", "PENGANTAR TEKNOLOGI INFORMASI & KOMUNIKASI", 
			"PENGANTAR REKAYASA SOFTWARE", "PENDIDIKAN AGAMA ISLAM", "PENDIDIKAN AGAMA KHATOLIK"]